coverage:
  precision: 2
  round: down
  status:
    project:
      contracts:
        target: 100
        flags: contracts
flags:
  contracts:
    paths:
      - coverage/contracts
ignore:
  - "contracts/mocks/**"
  - "contracts/echidna/**"
  - "contracts/tools/**"
